PACKAGE_NAME="optee-tools"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="teeload"
BUILT_MODULE_LOCATION[0]="teeload"
DEST_MODULE_LOCATION[0]="/updates"
BUILT_MODULE_NAME[1]="readcon"
BUILT_MODULE_LOCATION[1]="readcon"
DEST_MODULE_LOCATION[1]="/updates"
MAKE[0]="make -C teeload KDIR=/usr/lib/modules/${kernelver}/build && make -C readcon KDIR=/usr/lib/modules/${kernelver}/build"
CLEAN="make -C teeload clean; make -C readcon clean"
AUTOINSTALL="yes"
